### ISSUE TITLE
hello can tell me check player have item on function

### ISSUE THREAD

**Issue by vanillla1** [BerkieBb/qb-target#21]
hello can tell me check player have item on function ?

  canInteract = function()
	  return Player.Functions.GetItemAmount("lockpick", true) > 1
  end,

**Comment by Archangelza1** [comment]
Hey vanilla

If you are wanting to do an item check

then you can use 

`item = 'handcuffs',`

If you only want to display an option when they have a specific item you can use 

`QBCore.Functions.HasItem`

From QBCore in order to return if they player has the item or not

Please feel free to ask anything else if I misunderstood your question 😄

**Comment by BerkieBb** [comment]
No it's actually different, let me write it out wait a second

**Comment by BerkieBb** [comment]
The Player.Functions table is btw server side thus won't work

**Comment by BerkieBb** [comment]
```lua
canInteract = function()
    local hasitem = nil
    QBCore.Functions.TriggerCallback('QBCore:HasItem', function(result)
        if result then
            hasitem = true
        else
            hasitem = false
        end
    end)
 
    while hasitem == nil do
        Wait(1)
    end

    return hasitem
end,
```
This is the way you should do it if you want to use the config, if you're using exports or it is in the client/main.lua of qb-target, then you can use this, you do have to define PlayerData with QBCore.Functions.GetPlayerData()
```lua
canInteract = function()
    for k, v in pairs(PlayerData.items)
        if v.name == "lockpick" then
            return true
        end
    end
end,
```

**Comment by vanillla1** [comment]
thank you all
